# Generated by Django 4.2.1 on 2023-05-17 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone', models.CharField(max_length=40, unique=True)),
                ('firstName', models.CharField(blank=True, max_length=100)),
                ('lastName', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('tailleur', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_type', models.CharField(blank=True, choices=[('owner', 'owner'), ('manager', 'manager'), ('collaborator', 'collaborator'), ('tailleur', 'tailleur')], default='owner', max_length=20)),
                ('archived', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1255)),
                ('images', models.FileField(blank=True, null=True, upload_to='uploads/albums')),
                ('archived', models.BooleanField(default=False)),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_qte', models.IntegerField(default=1)),
                ('total', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'api_fewnu_compta_article',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=512)),
                ('archived', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_fewnu_compta_category',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=250)),
                ('telephone', models.CharField(max_length=30)),
                ('adresse', models.CharField(max_length=250)),
                ('pays', models.CharField(blank=True, max_length=255, null=True)),
                ('Ville', models.CharField(max_length=255, null=True)),
                ('sexe', models.CharField(choices=[('femme', 'femme'), ('homme', 'homme')], default='femme', max_length=10)),
                ('cou', models.IntegerField(blank=True, null=True)),
                ('epaule', models.IntegerField(blank=True, null=True)),
                ('longueur_boubou', models.IntegerField(blank=True, null=True)),
                ('longueur_manche', models.IntegerField(blank=True, null=True)),
                ('cuisse', models.IntegerField(blank=True, null=True)),
                ('longueur_pantalon', models.IntegerField(blank=True, null=True)),
                ('hanche', models.IntegerField(blank=True, null=True)),
                ('ceinture', models.IntegerField(blank=True, null=True)),
                ('tour_bras', models.IntegerField(blank=True, null=True)),
                ('poitrine', models.IntegerField(blank=True, null=True)),
                ('taille', models.IntegerField(blank=True, null=True)),
                ('longueur_robe', models.IntegerField(blank=True, null=True)),
                ('longueur_poitrine', models.IntegerField(blank=True, null=True)),
                ('bretelle', models.IntegerField(blank=True, null=True)),
                ('longueur_jupe', models.IntegerField(blank=True, null=True)),
                ('longueur_haut', models.IntegerField(blank=True, null=True)),
                ('blouse', models.IntegerField(blank=True, null=True)),
                ('autre', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('archived', models.BooleanField(default=False)),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_fewnu_compta_client',
            },
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ENCOURS', 'ENCOURS'), ('ENVOYE', 'ENVOYE'), ('PAYE', 'PAYE'), ('ANNULE', 'ANNULE')], default='ENCOURS', max_length=10)),
                ('matricule', models.CharField(blank=True, max_length=32, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/depenses/')),
                ('total', models.IntegerField(blank=True, null=True)),
                ('archived', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'api_fewnu_compta_depense',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=125)),
                ('telephone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('addresse', models.CharField(max_length=125)),
                ('numero_cni', models.CharField(max_length=32)),
                ('salaire', models.IntegerField()),
                ('photo', models.ImageField(blank=True, upload_to='uploads/employee')),
                ('contrat', models.CharField(max_length=125)),
                ('poste', models.CharField(max_length=125)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(auto_now_add=True)),
                ('archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('libelle', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=512)),
                ('qte', models.IntegerField()),
                ('min_stock', models.IntegerField()),
                ('prix_achat', models.IntegerField()),
                ('prix_vente', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('archived', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product', to='api_fewnu_compta.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_fewnu_compta_produit',
            },
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ENCOURS', 'ENCOURS'), ('ENVOYE', 'ENVOYE'), ('PAYE', 'PAYE'), ('ANNULE', 'ANNULE')], default='ENCOURS', max_length=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('facture', models.FileField(blank=True, null=True, upload_to='images/ventes/')),
                ('archived', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_fewnu_compta.customer')),
                ('products', models.ManyToManyField(through='api_fewnu_compta.Article', to='api_fewnu_compta.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_fewnu_compta_vente',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(blank=True, null=True, upload_to='uploads/albums')),
                ('archived', models.BooleanField(default=False)),
                ('albumId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api_fewnu_compta.album')),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PAYE', 'PAYE'), ('AVANCE', 'AVANCE')], default='AVANCE', max_length=10)),
                ('montant', models.IntegerField(blank=True, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('id_employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employe', to='api_fewnu_compta.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('firstName', models.CharField(max_length=250)),
                ('lastName', models.CharField(max_length=250)),
                ('telephone', models.CharField(max_length=30)),
                ('adresse', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('archived', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fournisseur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_fewnu_compta_fournisseur',
            },
        ),
        migrations.CreateModel(
            name='DepenseArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_qte', models.IntegerField(default=1)),
                ('total', models.IntegerField(default=0)),
                ('depense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depense_aticle', to='api_fewnu_compta.depense')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_fewnu_compta.product')),
            ],
            options={
                'db_table': 'api_fewnu_compta_depense_article',
                'unique_together': {('products', 'depense')},
            },
        ),
        migrations.AddField(
            model_name='depense',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_fewnu_compta.fournisseur'),
        ),
        migrations.AddField(
            model_name='depense',
            name='products',
            field=models.ManyToManyField(through='api_fewnu_compta.DepenseArticle', to='api_fewnu_compta.product'),
        ),
        migrations.AddField(
            model_name='depense',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('raisonSocial', models.CharField(blank=True, max_length=250, null=True)),
                ('telephone', models.CharField(blank=True, max_length=30, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('formJuridiqu', models.CharField(blank=True, max_length=250, null=True)),
                ('adresse', models.CharField(blank=True, max_length=250, null=True)),
                ('pays', models.CharField(blank=True, max_length=250, null=True)),
                ('region', models.CharField(blank=True, max_length=250, null=True)),
                ('ville', models.CharField(blank=True, max_length=250, null=True)),
                ('numeroSiret', models.CharField(blank=True, max_length=250, null=True)),
                ('codePostal', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('archived', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_fewnu_compta_company',
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroCommande', models.CharField(max_length=4, unique=True)),
                ('nom_tissu', models.CharField(blank=True, max_length=255, null=True)),
                ('metre_tissu', models.IntegerField(blank=True, null=True)),
                ('modele', models.FileField(blank=True, null=True, upload_to='images/')),
                ('date_livraison', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('montant', models.FloatField()),
                ('montant_paye', models.FloatField(blank=True, default=0, null=True)),
                ('montant_restant', models.FloatField(blank=True, default=0, null=True)),
                ('statut', models.CharField(blank=True, choices=[('nouvelle', 'Nouvelle'), ('livree', 'Livree'), ('encours', 'ENCOURS'), ('terminee', 'Terminee')], default='nouvelle', max_length=300, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('date_commande', models.DateTimeField(default=django.utils.timezone.now)),
                ('clientId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_fewnu_compta.customer')),
                ('createdBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_fewnu_compta.product'),
        ),
        migrations.AddField(
            model_name='article',
            name='vente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='api_fewnu_compta.vente'),
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together={('products', 'vente')},
        ),
    ]
