# Generated by Django 4.2.1 on 2023-05-17 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_fewnu_compta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='numeroCommande',
            new_name='numero_commande',
        ),
    ]
