# Generated by Django 4.2.1 on 2023-05-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_fewnu_compta", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commande",
            old_name="numeroCommande",
            new_name="numero_commande",
        ),
        migrations.RemoveField(
            model_name="user",
            name="email",
        ),
        migrations.AlterField(
            model_name="commande",
            name="statut",
            field=models.CharField(
                blank=True,
                choices=[
                    ("nouvelle", "Nouvelle"),
                    ("livree", "Livree"),
                    ("encours", "Encours"),
                    ("terminee", "Terminee"),
                ],
                default="nouvelle",
                max_length=300,
                null=True,
            ),
        ),
    ]
