# Generated by Django 4.1.1 on 2023-04-18 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_fewnu_compta', '0002_alter_customer_createdby'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_tissu', models.CharField(blank=True, max_length=255, null=True)),
                ('metre_tissu', models.IntegerField(blank=True, null=True)),
                ('modele', models.CharField(blank=True, max_length=255, null=True)),
                ('date_livraison', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=20)),
                ('statut', models.CharField(blank=True, choices=[('nouvelle', 'nouvelle'), ('livree', 'livree'), ('encours', 'encours')], default='encours', max_length=300, null=True)),
                ('clientId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_fewnu_compta.customer')),
                ('createdBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
