# Generated by Django 4.2.1 on 2023-05-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_fewnu_compta', '0002_rename_numerocommande_commande_numero_commande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(blank=True, choices=[('nouvelle', 'Nouvelle'), ('livree', 'Livree'), ('encours', 'Encours'), ('terminee', 'Terminee')], default='nouvelle', max_length=300, null=True),
        ),
    ]
