# Generated by Django 4.1 on 2022-08-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_fewnu_compta', '0002_remove_article_qte'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='qte',
            field=models.IntegerField(default=1),
        ),
    ]
