# Generated by Django 4.2.1 on 2023-05-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "api_fewnu_compta",
            "0002_rename_numerocommande_commande_numero_commande_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, unique=True, verbose_name="Email"
            ),
        ),
    ]
