# Generated by Django 4.1 on 2022-08-26 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_fewnu_compta', '0003_article_qte'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='qte',
            new_name='prod_qte',
        ),
    ]
