# Generated by Django 4.1.1 on 2023-04-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_fewnu_compta', '0003_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
