# Generated by Django 4.2.1 on 2023-06-12 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api_fewnu_compta", "0003_user_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commande",
            name="montant_paye",
        ),
        migrations.RemoveField(
            model_name="commande",
            name="montant_restant",
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant_paye", models.FloatField(blank=True, default=0, null=True)),
                (
                    "montant_restant",
                    models.FloatField(blank=True, default=0, null=True),
                ),
                ("date_transaction", models.DateTimeField(auto_now_add=True)),
                (
                    "commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api_fewnu_compta.commande",
                    ),
                ),
            ],
        ),
    ]
