# Generated by Django 4.2.1 on 2023-06-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_fewnu_compta", "0004_remove_commande_montant_paye_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
