# Generated by Django 4.1.1 on 2023-04-18 11:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_fewnu_compta', '0004_commande_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='date_commande',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
