# Generated by Django 4.1 on 2022-08-26 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_fewnu_compta', '0004_rename_qte_article_prod_qte'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepenseArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_qte', models.IntegerField(default=1)),
                ('total', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'api_fewnu_compta_depense_article',
            },
        ),
        migrations.RemoveField(
            model_name='depense',
            name='product_list',
        ),
        migrations.AddField(
            model_name='depense',
            name='products',
            field=models.ManyToManyField(through='api_fewnu_compta.DepenseArticle', to='api_fewnu_compta.product'),
        ),
        migrations.AlterField(
            model_name='depense',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_fewnu_compta.fournisseur'),
        ),
        migrations.AlterField(
            model_name='depense',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='depense',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='depensearticle',
            name='depense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depense_aticle', to='api_fewnu_compta.depense'),
        ),
        migrations.AddField(
            model_name='depensearticle',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_fewnu_compta.product'),
        ),
        migrations.AlterUniqueTogether(
            name='depensearticle',
            unique_together={('products', 'depense')},
        ),
    ]
