# Generated by Django 4.2.1 on 2023-06-12 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api_fewnu_compta", "0005_transaction_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="commande",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commandes",
                to="api_fewnu_compta.transaction",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="commande",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="api_fewnu_compta.commande",
            ),
        ),
    ]
