# Generated by Django 4.1 on 2022-09-05 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_fewnu_compta', '0005_depensearticle_remove_depense_product_list_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('raisonSocial', models.CharField(blank=True, max_length=250, null=True)),
                ('formJuridiqu', models.CharField(blank=True, max_length=250, null=True)),
                ('adresse', models.CharField(blank=True, max_length=250, null=True)),
                ('pays', models.CharField(blank=True, max_length=250, null=True)),
                ('region', models.CharField(blank=True, max_length=250, null=True)),
                ('ville', models.CharField(blank=True, max_length=250, null=True)),
                ('numeroSiret', models.CharField(blank=True, max_length=250, null=True)),
                ('codePostal', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('archived', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_fewnu_compta_company',
            },
        ),
    ]
