# Generated by Django 4.1.1 on 2023-04-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_fewnu_compta', '0005_commande_date_commande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='montant',
            field=models.FloatField(),
        ),
    ]
