# Generated by Django 4.1.1 on 2023-04-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_fewnu_compta', '0006_alter_commande_montant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='modele',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
