# Generated by Django 4.2.1 on 2023-08-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_fewnu_compta', '0006_alter_customer_adresse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Ville',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
