# Generated by Django 4.2.1 on 2023-08-09 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_fewnu_compta', '0007_alter_customer_ville'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='date_debut',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='date_fin',
        ),
    ]
