# Generated by Django 4.2.1 on 2023-06-12 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api_fewnu_compta", "0007_remove_commande_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="commande",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commandes",
                to="api_fewnu_compta.transaction",
            ),
        ),
    ]
