# Generated by Django 4.1.1 on 2023-04-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_fewnu_compta', '0007_alter_commande_modele'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='clientId',
        ),
        migrations.AddField(
            model_name='commande',
            name='clientId',
            field=models.ManyToManyField(null=True, to='api_fewnu_compta.customer'),
        ),
    ]
