# Generated by Django 4.1.1 on 2023-04-20 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_fewnu_compta', '0008_remove_commande_clientid_commande_clientid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='clientId',
        ),
        migrations.AddField(
            model_name='commande',
            name='clientId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_fewnu_compta.customer'),
        ),
    ]
