# Generated by Django 4.2.1 on 2023-08-09 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_fewnu_compta', '0008_remove_employee_date_debut_remove_employee_date_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='createdBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
