# Generated by Django 4.1.1 on 2023-05-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_fewnu_compta', '0009_remove_commande_clientid_commande_clientid'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='images',
            field=models.FileField(blank=True, default='/albums/tayeur.png', null=True, upload_to='uploads/albums'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='images',
            field=models.FileField(blank=True, default='/albums/tayeur.png', upload_to='uploads/albums'),
        ),
    ]
