# Generated by Django 4.1 on 2022-09-20 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_fewnu_compta', '0009_alter_vente_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depenses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_fewnu_compta.depense')),
                ('ventes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_fewnu_compta.vente')),
            ],
            options={
                'db_table': 'api_fewnu_compta_statistic',
            },
        ),
    ]
