# Generated by Django 4.1.1 on 2023-05-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_fewnu_compta', '0010_album_images_alter_photo_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='images',
            field=models.FileField(blank=True, default='/albums/tayeur.png', null=True, upload_to='uploads/albums/'),
        ),
    ]
