# Generated by Django 4.2.1 on 2023-08-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_fewnu_compta', '0010_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='images',
            field=models.FileField(upload_to=''),
        ),
    ]
