# Generated by Django 4.1 on 2022-10-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_fewnu_compta', '0011_depense_image_delete_statistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='depense',
            name='status',
            field=models.CharField(choices=[('ENCOURS', 'ENCOURS'), ('ENVOYE', 'ENVOYE'), ('PAYE', 'PAYE'), ('ANNULE', 'ANNULE')], default='ENCOURS', max_length=10),
        ),
    ]
