# Generated by Django 4.1.1 on 2023-05-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_fewnu_compta', '0011_alter_album_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='uploads/albums'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='uploads/albums'),
        ),
    ]
