# Generated by Django 4.1.1 on 2023-05-04 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_fewnu_compta', '0012_alter_album_images_alter_photo_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='album',
            new_name='albumId',
        ),
    ]
