# Generated by Django 4.1 on 2022-10-12 15:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_fewnu_compta', '0012_depense_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='depense',
            name='matricule',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
