# Generated by Django 4.1 on 2022-10-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_fewnu_compta', '0014_alter_depense_matricule'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='facture',
            field=models.ImageField(blank=True, null=True, upload_to='images/ventes/'),
        ),
    ]
