# Generated by Django 4.2.1 on 2023-05-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_fewnu_compta', '0014_album_createdby_photo_createdby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(blank=True, choices=[('nouvelle', 'nouvelle'), ('livree', 'livree'), ('encours', 'encours')], default='nouvelle', max_length=300, null=True),
        ),
    ]
