# Generated by Django 4.2.1 on 2023-05-13 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_fewnu_compta', '0015_alter_commande_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='montant_paye',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='montant_restant',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
