# Generated by Django 4.1 on 2022-10-12 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_fewnu_compta', '0015_vente_facture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='facture',
            field=models.FileField(blank=True, null=True, upload_to='images/ventes/'),
        ),
    ]
