# Generated by Django 4.2.1 on 2023-08-12 19:06

import api_fewnu_compta.models.parametre
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_fewnu_compta', '0015_profile_adresse_profile_email_profile_firstname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('numWhtsapp', models.CharField(blank=True, max_length=120, null=True)),
                ('pays', models.CharField(blank=True, max_length=120, null=True)),
                ('ville', models.CharField(blank=True, max_length=120, null=True)),
                ('profile_image', models.ImageField(blank=True, default='/tayeur/tayeur-logo.png', null=True, upload_to=api_fewnu_compta.models.parametre.logo_directory_path)),
                ('nom_attelier', models.CharField(blank=True, max_length=100)),
                ('userId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
