# Generated by Django 4.1 on 2022-11-11 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_fewnu_compta', '0016_alter_vente_facture'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='telephone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
