# Generated by Django 4.1 on 2022-11-11 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_fewnu_compta', '0016_alter_vente_facture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=125)),
                ('numero_telephone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('numero_cni', models.IntegerField()),
                ('salaire', models.IntegerField()),
                ('photo', models.ImageField(upload_to='uploads/')),
                ('contrat', models.CharField(max_length=125)),
                ('post', models.CharField(max_length=125)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
