# Generated by Django 4.2.1 on 2023-08-12 19:12

import api_fewnu_compta.models.parametre
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_fewnu_compta', '0016_parametre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametre',
            name='profile_image',
            field=models.ImageField(blank=True, default='tayeur/tayeur-logo.png', null=True, upload_to=api_fewnu_compta.models.parametre.logo_directory_path),
        ),
    ]
