# Generated by Django 4.2.1 on 2023-05-16 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_fewnu_compta", "0017_alter_user_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="email",
        ),
    ]
