# Generated by Django 4.2.1 on 2023-08-12 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_fewnu_compta', '0017_alter_parametre_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profile_images/')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_fewnu_compta.parametre')),
            ],
        ),
    ]
