# Generated by Django 4.1 on 2022-11-12 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_fewnu_compta', '0018_rename_post_employee_addresse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
