# Generated by Django 4.2.1 on 2023-05-16 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_fewnu_compta", "0018_remove_user_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commande",
            old_name="statut",
            new_name="statuts",
        ),
    ]
