# Generated by Django 4.1 on 2022-11-12 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_fewnu_compta', '0017_company_telephone'),
        ('api_fewnu_compta', '0018_rename_post_employee_addresse_and_more'),
    ]

    operations = [
    ]
