# Generated by Django 4.2.1 on 2023-05-16 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_fewnu_compta", "0019_rename_statut_commande_statuts"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commande",
            old_name="statuts",
            new_name="statut",
        ),
    ]
