# Generated by Django 4.1 on 2022-11-12 01:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_fewnu_compta', '0019_merge_20221112_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PAYE', 'PAYE'), ('AVANCE', 'AVANCE')], default='AVANCE', max_length=10)),
                ('montant', models.IntegerField(blank=True, null=True)),
                ('id_employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_fewnu_compta.employee')),
            ],
        ),
    ]
