# Generated by Django 4.1 on 2022-11-12 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_fewnu_compta', '0019_merge_20221112_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
