# Generated by Django 4.1 on 2022-11-12 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_fewnu_compta', '0019_employee_archived'),
        ('api_fewnu_compta', '0019_merge_20221112_0023'),
    ]

    operations = [
    ]
