# Generated by Django 4.1 on 2022-11-12 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_fewnu_compta', '0020_alter_user_phone'),
        ('api_fewnu_compta', '0020_merge_0019_employee_archived_0019_merge_20221112_0023'),
    ]

    operations = [
    ]
