# Generated by Django 4.2.1 on 2023-08-12 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_fewnu_compta', '0020_rename_image_parametreimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametreimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tayeurImages/'),
        ),
    ]
