# Generated by Django 4.2.1 on 2023-08-12 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_fewnu_compta', '0021_alter_parametreimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parametreimage',
            old_name='profile',
            new_name='parametre',
        ),
    ]
