# Generated by Django 4.1 on 2022-11-12 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_fewnu_compta', '0020_paiement'),
        ('api_fewnu_compta', '0021_merge_20221112_0231'),
    ]

    operations = [
    ]
