# Generated by Django 4.1 on 2022-11-12 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_fewnu_compta', '0022_merge_0020_paiement_0021_merge_20221112_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
