# Generated by Django 4.2.1 on 2023-05-17 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_fewnu_compta", "0022_commande_numero_commande_alter_commande_statut"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commande",
            name="numero_commande",
        ),
        migrations.AlterField(
            model_name="commande",
            name="statut",
            field=models.CharField(
                blank=True,
                choices=[
                    ("nouvelle", "nouvelle"),
                    ("livree", "livree"),
                    ("encours", "encours"),
                    ("terminee", "terminee"),
                ],
                default="nouvelle",
                max_length=300,
                null=True,
            ),
        ),
    ]
