# Generated by Django 4.2.1 on 2023-08-12 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_fewnu_compta', '0022_rename_profile_parametreimage_parametre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametre',
            name='nom_attelier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
