# Generated by Django 4.1 on 2022-11-12 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_fewnu_compta', '0023_paiement_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='numero_cni',
            field=models.CharField(max_length=32),
        ),
    ]
