# Generated by Django 4.1.3 on 2023-08-18 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_fewnu_compta', '0023_alter_parametre_nom_attelier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entree',
            name='nom_entree',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
