# Generated by Django 4.1.3 on 2023-08-19 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_fewnu_compta', '0024_alter_entree_nom_entree'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='createdBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
