# Generated by Django 4.1 on 2022-11-12 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_fewnu_compta', '0024_alter_employee_numero_cni'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COU', models.IntegerField(blank=True, null=True)),
                ('EPAULE', models.IntegerField(blank=True, null=True)),
                ('MANCHES', models.IntegerField(blank=True, null=True)),
                ('CEINTURE', models.IntegerField(blank=True, null=True)),
                ('TOURS_DE_BRAS', models.IntegerField(blank=True, null=True)),
                ('TOURS_DE_HANCHES', models.IntegerField(blank=True, null=True)),
                ('TOURS_DE_CUISSE', models.IntegerField(blank=True, null=True)),
                ('LONGUEUR_HAUT', models.IntegerField(blank=True, null=True)),
                ('LONGUEUR_BAS', models.IntegerField(blank=True, null=True)),
                ('LONGUEUR_BOUBOU', models.IntegerField(blank=True, null=True)),
                ('LONGUEUR_JUPE', models.IntegerField(blank=True, null=True)),
                ('POITRINE', models.IntegerField(blank=True, null=True)),
                ('TOURS_DE_TAILLE', models.IntegerField(blank=True, null=True)),
                ('LONGUEUR_BRAS', models.IntegerField(blank=True, null=True)),
                ('LONGUEUR_ROBE', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='sexe',
            field=models.CharField(choices=[('femme', 'femme'), ('homme', 'homme')], default='femme', max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='mesure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_fewnu_compta.mesure'),
        ),
    ]
