# Generated by Django 4.1 on 2022-11-12 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_fewnu_compta', '0024_alter_employee_numero_cni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='id_employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employe', to='api_fewnu_compta.employee'),
        ),
    ]
