# Generated by Django 4.1 on 2022-11-12 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_fewnu_compta', '0026_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='images',
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='uploads/albums')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api_fewnu_compta.album')),
            ],
        ),
    ]
