# Generated by Django 4.1 on 2022-11-12 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_fewnu_compta', '0028_rename_photos_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
