# Generated by Django 4.1 on 2022-11-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_fewnu_compta', '0029_album_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
