# Generated by Django 4.1 on 2022-11-14 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_fewnu_compta', '0025_mesure_customer_sexe_customer_mesure'),
        ('api_fewnu_compta', '0030_photo_archived'),
    ]

    operations = [
    ]
